name: Build and Push Docker Image

on:
  push:
    path-ignore:
      - "README.md"
      - "LICENSE"
      - "example/**"
      - "docker-compose.example.yml"
      - "docker-compose.yml"
      - "config.example.toml"
      - "config_example.json"
    branches:
      - master
  pull_request:
    path-ignore:
      - "README.md"
      - "LICENSE"
      - "example/**"
      - "docker-compose.yml"
      - "docker-compose.example.yml"
      - "config.example.toml"
      - "config_example.json"
    branches:
      - master

env:
  IMAGE_NAME_GITHUB: nerdneilsfield/deeplx-load-balancer
  IMAGE_NAME_DOCKERHUB: nerdneils/deeplx-load-balancer

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME_DOCKERHUB }}:latest